#! /bin/sh

#   __                         _____       __         .__     
# _/  |________   ____   _____/ ____\_____/  |_  ____ |  |__  
# \   __\_  __ \_/ __ \_/ __ \   __\/ __ \   __\/ ___\|  |  \ 
#  |  |  |  | \/\  ___/\  ___/|  | \  ___/|  | \  \___|   Y  \
#  |__|  |__|    \___  >\___  >__|  \___  >__|  \___  >___|  /
#                    \/     \/          \/          \/     \/ 

#####################
# Information
#####################

# Packages

if command -v pacman >/dev/null
then
  pkg="$(pacman -Qq | wc -l)"
elif  command -v dpkg >/dev/null
then
  pkg="$(dpkg -l | wc -l)"
elif  command -v emerge >/dev/null
then
  pkg="$(cd /var/db/pkg/ && ls -d */* | wc -l)"
elif  command -v xbps-query >/dev/null
then
    pkg="$(xbps-query -l | wc -l)"
else
  pkg="$(rpm -qa | wc -l)"
fi

# Get user
user="${USER-$(id -u -n)}"

# Get host
host="$(uname -n)"

# Get OS
. /etc/os-release
os="$NAME"

# Get uptime
uptime="$(echo $(awk '{print $1}' /proc/uptime) / 3600 | bc)"

# Shell
shell="${SHELL##*/}"

#####################
# Display protocol
#####################

[ "$DISPLAY" ] && displayprot="x11"
[ "$WAYLAND_DISPLAY" ] && displayprot="wayland"
[ ! "$displayprot" ] && displayprot="tty"

wm="$XDG_CURRENT_DESKTOP"
[ "$wm" ] || wm="$DESKTOP_SESSION"

#####################
# Window Manager
#####################

[ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
  id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
  id=${id##* }
  wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
    grep '^_NET_WM_NAME' | cut -d\" -f 2)
}

#####################
# For non-EWH WMs
#####################

[ ! "$wm" ] || [ "$wm" = "LG3D" ] &&
  wm=$(
    ps -e | grep -m 1 -o \
      -e "sway" \
      -e "kiwmi" \
      -e "wayfire" \
      -e "sowm" \
      -e "catwm" \
      -e "fvwm" \
      -e "dwm" \
      -e "2bwm" \
      -e "monsterwm" \
      -e "tinywm" \
      -e "xmonad"
  )

#####################
# Memory
#####################
total_mem=$(free -m | grep Mem: | awk '{print $2}')
mem_used=$(free -m | grep Mem: | awk '{print $3}')
mem="$mem_used/$total_mem"

#####################
# Disk
#####################
total_disk=$(echo $(df -k --output=size / | tail -n1) / 1048576 | bc)
disk_used=$(echo $(df -k --output=used / | tail -n1) / 1048576 | bc)
disk="$disk_used/$total_disk"

#####################
# Colors
#####################

c0='[0m'
c1='[31m'
c2='[32m'
c3='[33m'
c4='[34m'
c5='[35m'
c6='[36m'
c7='[37m'
c8='[38m'
c9='^[[37m'

#####################
# Art
#####################

ARTR1="${c2}           _-_       "
ARTR2="${c2}        /~~   ~~\    "
ARTR3="${c2}     /~~         ~~\ "
ARTR4="${c2}    {               }"
ARTR5="${c2}     \  _-     -_  / "
ARTR6="${c1}       ~  \\\ //  ~   "
ARTR7="${c1}    _- -   | | _- _  "
ARTR8="${c1}      _ -  | |   -_  "
ARTR9="${c1}          // \\\      "


#####################
# Main Print
#####################

cat <<-EOF

 ${ARTR1}  ${c5}host${c0}    ${c1}•••   ${host}
 ${ARTR2}  ${c5}user${c0}    ${c2}•••   ${user}
 ${ARTR3}  ${c5}shell${c0}   ${c3}•••   ${shell}
 ${ARTR4}  ${c5}wm${c0}      ${c4}•••   ${wm}
 ${ARTR5}  ${c5}os${c0}      ${c5}•••   ${os}
 ${ARTR6}  ${c5}pkg${c0}     ${c6}•••   ${pkg}
 ${ARTR7}  ${c5}uptime${c0}  ${c7}•••   ${uptime} 
 ${ARTR8}  ${c5}mem${c0}     ${c4}•••   ${mem}
 ${ARTR9}  ${c5}disk${c0}    ${c6}•••   ${disk}

EOF
